import { Poppins } from 'next/font/google'
import './globals.css'
import Nav from "./components/Nav";

const poppins = Poppins({ weight: ["100", "300", "400", "500", "600"], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="px-3"><Nav /></div>
        {children}
      </body>
    </html>
  )
}
